# Local dev Compose
version: '3.0'
services:
  redis:
    image: redis:alpine
    volumes:
      - /mnt/gp_files/reddit_rpan/redis:/data
    restart: always
    command: "redis-server --appendonly yes"
    expose:
      - 6379
    ports:
      - 127.0.0.1:6379:6379
