"""seed checked

Revision ID: b0e0a49e57b7
Revises: 8830b5799b1c
Create Date: 2019-08-24 23:41:00.363055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e0a49e57b7'
down_revision = '8830b5799b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed_responses', sa.Column('checked', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seed_responses', 'checked')
    # ### end Alembic commands ###
